[package]
resolver = "2"
name = "minesweeper-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
tinyvec = "1.8"
log = "0.4"

[dev-dependencies]
serde_json = "1.0"
