[package]
name = "frontend"
edition = "2021"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.6", features = ["csr", "nightly"] }
minesweeper = { path="../minesweeper" }
