# fly.toml app configuration file generated for minesweeper-io on 2024-02-02T21:26:55-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minesweeper-io"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024

[mounts]
  source="mines_db"
  destination="/app/db"

[env]
  DATABASE_URL="sqlite:db/mines.db"
  # rest of env is in secrets
