[package]
name = "web-auth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
axum-login = { workspace = true, optional = true }
chrono = { workspace = true }
cfg-if = { workspace = true }
futures = { workspace = true, optional = true }
http = { workspace = true }
log = { workspace = true }
oauth2 = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "time", "chrono", "runtime-tokio"], optional = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, optional = true }
tower-sessions = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
getrandom = { workspace = true }

[features]
ssr = [
    "dep:axum",
    "dep:axum-login",
    "dep:futures",
    "dep:oauth2",
    "dep:sqlx",
    "dep:tokio",
    "dep:tower-sessions",
    "dep:tracing",
    "dep:reqwest",
]
