[package]
name = "game-manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
minesweeper-lib = { workspace = true }
web-auth = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
chrono = { workspace = true }
cfg-if = { workspace = true }
futures = { workspace = true, optional = true }
http = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "time", "chrono", "runtime-tokio"], optional = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
getrandom = { workspace = true }

[features]
ssr = [
    "dep:axum",
    "dep:futures",
    "dep:sqlx",
    "dep:tokio",
    "web-auth/ssr"
]
